version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/mydb
      - NODE_PUBLIC_ENVIRONMENT=docker
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: client
    restart: always
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  mongo-data:
