apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: natours
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: salah529/natours-frontend:latest
          ports:
            - containerPort: 4173
          env:
            - name: REACT_APP_API_URL
              value: http://backend-service:3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: natours
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - port: 4173
      targetPort: 4173
