name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Docker Compose plugin if needed
      - name: Check Docker Compose
        run: docker compose version

      # Build Frontend
      - name: Build Frontend
        working-directory: client
        run: |
          npm ci
          npm run build

      # Build Backend
      - name: Build Backend
        working-directory: server
        run: |
          npm ci
          npm run build

      # Start all services using docker compose
      - name: Start services
        run: |
          docker compose -f docker-compose.yml up -d --build

      # Optional: Wait for MongoDB to be ready
      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to be ready..."
          for i in {1..20}; do
            docker exec mongo mongo --eval "db.adminCommand('ping')" && break
            echo "Mongo not ready yet... retrying in 3s"
            sleep 3
          done

      # Push Docker images (optional, only on main branch)
      - name: Push Docker images
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker tag natours-frontend $DOCKER_USER/natours-frontend:latest
          docker tag natours-backend $DOCKER_USER/natours-backend:latest
          docker push $DOCKER_USER/natours-frontend:latest
          docker push $DOCKER_USER/natours-backend:latest
