name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and start services with Docker Compose
      - name: Build and start services
        run: |
          docker-compose -f docker-compose.ci.yml up -d --build

      # Wait for MongoDB to be ready
      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to be ready..."
          until docker exec mongo mongo --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
            sleep 2
          done

      # Run backend tests (optional)
      - name: Run backend tests
        run: |
          docker exec server npm run test

      # Run frontend tests (optional)
      - name: Run frontend tests
        run: |
          docker exec client npm run test

      # Push Docker images if on main
      - name: Push Docker images
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker-compose -f docker-compose.ci.yml push
