name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Build Frontend
      - name: Build Frontend
        working-directory: client
        run: |
          npm ci
          npm run build

      # Build Backend
      - name: Build Backend
        working-directory: server
        run: |
          npm ci
          npm run build

      # Build Docker images
      - name: Build Docker images
        run: |
          docker build -t natours-frontend ./client
          docker build -t Natours-backend ./server

      # Push Docker images
      - name: Push Docker images
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker tag Natours-frontend $DOCKER_USER/natours-frontend:latest
          docker tag natours-backend $DOCKER_USER/natours-backend:latest
          docker push $DOCKER_USER/natours-frontend:latest
          docker push $DOCKER_USER/natours-backend:latest
